name: Auto Update

permissions: {}

on:
  schedule:
    - cron: "0 2 * * *" # Run daily at 2 AM UTC
  workflow_dispatch:

jobs:
  update:
    name: Auto Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: oxc-project/setup-rust@4f86b5d871ae7d24bc420e578be68964ab09e5cc # v1.0.15
      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6

      - name: Update globals package
        run: pnpm update globals

      - name: Run xtask to update globals
        run: cargo run -p xtask

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        id: cpr
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: Auto update globals from upstream
          branch: update
          branch-suffix: timestamp
          title: Auto update globals from upstream
          assignees: Boshen
          base: main

      - uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        if: steps.cpr.outputs.pull-request-operation == 'created'
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
